import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/SessionContext";
import ThemeProvider, { ThemeContext } from "./context/ThemeContext";
import { useContext } from "react";
import App from "./App";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <App>{children}</App>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
